### ISSUE TITLE
Drop-in replacement for `fft`

### ISSUE THREAD

**Issue by milankl** [JuliaApproximation/GenericFFT.jl#1]
At the moment GenericFFT.jl also exports `fft` from FFTW.jl, such that type promotions take place when using it
```julia
julia> using GenericFFT, SoftPosit

julia> a = Posit16.(randn(8))
8-element Vector{Posit16}:
 Posit16(-0.88500977)
 Posit16(-2.5810547)
 Posit16(-0.9567871)
  Posit16(1.7719727)
 Posit16(-1.2495117)
 Posit16(-0.043945312)
  Posit16(1.4433594)
 Posit16(-0.9428711)

julia> fft(a)
8-element Vector{ComplexF32}:
 -3.4438477f0 + 0.0f0im
 -3.3491898f0 + 2.2744694f0im
 -2.6210938f0 + 3.4541016f0im
  4.0781937f0 - 2.5258236f0im
 0.14794922f0 + 0.0f0im
  4.0781937f0 + 2.5258236f0im
 -2.6210938f0 - 3.4541016f0im
 -3.3491898f0 - 2.2744694f0im

julia> GenericFFT.generic_fft(a)
8-element Vector{Complex{Posit16}}:
  Posit16(-3.444336) + Posit16(0.0)im
 Posit16(-3.3486328) + Posit16(2.2734375)im
 Posit16(-2.6210938) + Posit16(3.4541016)im
   Posit16(4.078125) - Posit16(2.5253906)im
 Posit16(0.14746094) + Posit16(0.0)im
   Posit16(4.076172) + Posit16(2.5273438)im
 Posit16(-2.6210938) - Posit16(3.4541016)im
 Posit16(-3.3486328) - Posit16(2.2753906)im
```
However, `generic_fft` calls the actual code from this repo. I guess in general the idea is to be able to do either
```julia
julia> using FFTW
julia> fft(a)
```
or
```julia
julia> using GenericFFT
julia> fft(a)
```
such that the interface is the same, regardless of which FFT implementation is imported. When the main functionality of other FFT implementations has been replicated here the only code changes necessary is which FFT implementation to import. Do you agree?

**Comment by daanhb** [comment]
I think this is the problem with your array a:
```julia
julia> using AbstractFFTs, SoftPosit, GenericFFT

julia> a = Posit16.(randn(8));

julia> AbstractFFTs.complexfloat(a)
8-element Vector{ComplexF32}:
 -1.0439453f0 + 0.0f0im
 -1.8217773f0 + 0.0f0im
 -1.0209961f0 + 0.0f0im
 0.97753906f0 + 0.0f0im
  0.6430664f0 + 0.0f0im
 -0.5083008f0 + 0.0f0im
 -0.9382324f0 + 0.0f0im
  1.1206055f0 + 0.0f0im
```
The conversion happens in AbstractFFTs.jl, right?

**Comment by milankl** [comment]
> I do see GenericFFT as an extension of FFTW, not as an alternative to it.

Yes, sorry, that's what I meant. `fft(::Vector{Float32})` or `fft(::Vector{Float64})` (or complex) should call FFTW because it's the most sophisticated implementation, but any other `T<:AbstractFloat` should then call `generic_fft` via `fft` from this package. However, at the moment this doesn't happen, as there are some type promotions happening in AbstractFFTs.jl

https://github.com/JuliaMath/AbstractFFTs.jl/blob/03ef58b6f1fc033cba090a24c94837013b9f3ab0/src/definitions.jl#L30-L35

E.g. when caling `fft` with `Float16` it's converted to `Float32`

**Comment by daanhb** [comment]
So the culprit is [here](https://github.com/JuliaMath/AbstractFFTs.jl/blob/03ef58b6f1fc033cba090a24c94837013b9f3ab0/src/definitions.jl#L30)

That means you could do:
```julia
julia> using GenericFFT, SoftPosit, AbstractFFTs

julia> AbstractFFTs.fftfloat(x::AbstractPosit) = x

julia> a = Posit8.(rand(8));

julia> fft(a)
8-element Vector{Complex{Posit8}}:
     Posit8(4.0) + Posit8(0.0)im
  Posit8(0.4375) + Posit8(0.140625)im
    Posit8(-1.0) + Posit8(0.25)im
 Posit8(-0.9375) - Posit8(0.6875)im
    Posit8(-0.5) + Posit8(0.0)im
    Posit8(-1.0) + Posit8(0.625)im
    Posit8(-1.0) - Posit8(0.25)im
  Posit8(0.4375) - Posit8(0.0625)im
```
The reason for the behaviour is `float(a)` does a conversion:
```julia
julia> typeof(float(a[1]))
Float32
```

**Comment by daanhb** [comment]
Hmm, this looks plausible, but it is always dangerous to change behaviour of a package dependency. Conceptually, there is no reason for GenericFFT to be more generic than AbstractFFTs. The latter should be the most general, making no assumptions whatsoever. Again purely conceptually, I think this is an issue for upstream. But then again, I don't see the harm in calling `float(a)` at a general level. Or is there? What would an issue with AbstractFFTs say?

Since Posit16 inherits from AbstractFloat, we have:
```julia
julia> zero(Posit16) isa AbstractFloat
true
```
And yet `float(a)` changes type, which is unexpected if a is already an AbstractFloat. Would it be possible to change that to `blasfloat(a)` or something like that?

**Comment by milankl** [comment]
I agree there's two issues here

- AbstractFFTs.jl converts floating-point types like Float16 that (if you ask me) shouldn't be converted and just throw some not implemented-error instead (If someone wants to do an FFT with Float16 they should either use GenericFFT or explicitly convert it to Float32 and use FFTW) We could try asking for a PR that disables that conversion, but it would be a breaking change. Alternatively, we could overwrite `AbstractFFTs.fftfloat` as described above.
- Posits are defined as `<:AbstractFloat` as they should somehow be treated as those, but then also not. It's a weird trade-off. I'm currently defining `float(::AbstractPosit)` as the conversion from a given posit format to a (wider) float format, similar as `float(1) = 1.0` or `float(BigFloat(1)) = 1.0`. Sure that could be changed, and I see your point that it "is unexpected if [...] already an AbstractFloat".

**Comment by daanhb** [comment]
Well, purity discussions are popular in Julia, but they are rarely decisive. I see your trade-off between making things work and keeping things clean. To be nitpicking, float(1) changes an integer to a float, and float(BigFloat(1)) does not actually change the type (BigFloat remains BigFloat) :-)

Even for Float16, which is not supported as a computational type but only as a storage type, we have `float(zero(Float16)) isa Float16`. On that point, this came as a surprise:
```
julia> using FFTW

julia> x = rand(Float16, 2); fft(x)
2-element Vector{ComplexF32}:
  0.50390625f0 + 0.0f0im
 -0.24609375f0 + 0.0f0im

julia> x = rand(Complex{Float16}, 2); fft(x)
ERROR: MethodError: no method matching plan_fft(::Vector{ComplexF16}, ::UnitRange{Int64})
```
That doesn't look right. We seem to recover from that and even retain the type:
```julia
julia> using GenericFFT

julia> x = rand(Complex{Float16}, 2); fft(x)
2-element Vector{ComplexF16}:
  Float16(0.2402) + Float16(0.986)im
 Float16(-0.1934) - Float16(0.3628)im
```

Anyway, since the whole point of GenericFFT is to enable FFTs for funny number types, it is probably a good idea to do as you suggest and add `fftfloat(x::AbstractFloat) = x`. I fail to see how that could break code, especially because we can only expect new users here, and it increases the chances for other packages to "just work".

It is probably best to understand and list exactly how this differs from what AbstractFFTs produces, and to add that to the tests here. If we find that it works well for our purposes, we can considering filing an issue upstream. Sounds like a plan?

**Comment by daanhb** [comment]
By the way, even without the change:
```julia
julia> a = Complex{Posit8}.(rand(8))
8-element Vector{Complex{Posit8}}:
     Posit8(0.625) + Posit8(0.0)im
 Posit8(0.1171875) + Posit8(0.0)im
 Posit8(0.0546875) + Posit8(0.0)im
    Posit8(0.9375) + Posit8(0.0)im
    Posit8(0.6875) + Posit8(0.0)im
    Posit8(0.6875) + Posit8(0.0)im
    Posit8(0.4375) + Posit8(0.0)im
   Posit8(0.34375) + Posit8(0.0)im

julia> fft(a)
8-element Vector{Complex{Posit8}}:
    Posit8(3.75) + Posit8(0.0)im
  Posit8(-0.875) + Posit8(0.25)im
    Posit8(0.75) + Posit8(0.4375)im
  Posit8(0.8125) - Posit8(0.28125)im
   Posit8(-0.25) + Posit8(0.0)im
    Posit8(0.75) + Posit8(0.5)im
    Posit8(0.75) - Posit8(0.4375)im
 Posit8(-0.9375) - Posit8(0.46875)im
```
The conversion in AbstractFFTs is only for real data, not for complex data. That also explains the outcome for `Complex{Float16}` above.

**Comment by milankl** [comment]
> Well, purity discussions are popular in Julia, but they are rarely decisive. I see your trade-off between making things work and keeping things clean. To be nitpicking, float(1) changes an integer to a float, and float(BigFloat(1)) does not actually change the type (BigFloat remains BigFloat) :-)

Yes 😄, I see how `float` has been somehow misused for SoftPosit.jl and I'll remember that for future releases. I never bumped into this inconsistency before, thanks for raising it.

> Even for Float16, which is not supported as a computational type but only as a storage type

I know this was the policy from Julia many years ago, but given the increasing hardware support of Float16, I believe Julia packages should drop that storage-only perspective. In the end, type-flexibility in Julia is an amazing feature to test less conventional number formats so I can see many people (like me) testing their arithmetics in an emulated fashion first.

> Anyway, since the whole point of GenericFFT is to enable FFTs for funny number types, it is probably a good idea to do as you suggest and add `fftfloat(x::AbstractFloat) = x`. I fail to see how that could break code, especially because we can only expect new users here, and it increases the chances for other packages to "just work".

Thanks yeah I like it. I understand it as "if you load GenericFFT, you get type-stable FFTs", which is probably what most users of this package would expect. 

> It is probably best to understand and list exactly how this differs from what AbstractFFTs produces, and to add that to the tests here. If we find that it works well for our purposes, we can considering filing an issue upstream. Sounds like a plan?

Perfect!!
