### ISSUE TITLE
Change Readme to mention Mikael Slevinsky?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/GenericFFT.jl#12]
It currently says:

> The code in this package was developed in the [FastTransforms.jl](https://github.com/JuliaApproximation/FastTransforms.jl) package, with contributions by many developers

But as far as I can remember the generic FFT code was entirely due to @MikaelSlevinsky. (Perhaps he can correct me if I'm mistaken.) So I would change "with contributions by many developers" to "by Mikael Slevinsky".

**Comment by daanhb** [comment]
Yes, thanks for bringing it up - I had simply looked at the number of people contributing to the main file when writing the README. Change applied!

**Comment by MikaelSlevinsky** [comment]
Hey this wasn't on my radar, but thanks!
