### ISSUE TITLE
Are some of the dependencies necessary?

### ISSUE THREAD

**Issue by cgeoga** [JuliaApproximation/GenericFFT.jl#3]
Part of the reason I opened the original issue in `FastTransforms.jl` is that I didn't love pulling in a ton of code and dependencies for something where I was using just a single function and that could stand alone. The single-file radix-2 FFT that I use in some packages ([for example](https://git.sr.ht/~cgeoga/HalfSpectral.jl/tree/master/item/src/radix2.jl)) has no dependencies. This package will naturally have a bigger scope than that, but I think some deps in the tree aren't super necessary:

- I would vote to remove `DSP` from the tree and remove the `DSP.conv` methods that this file defines. That's the only place where it's used, and if those extra methods are valuable I think it would make more sense for `DSP` to pull in this package and define those methods, not vice versa.
- I'm not sure why `DoubleFloats` is in the tree at all. It looks like it's only necessary for tests and the README.
- I personally would choose to skip `Reexport`, but that barely pulls in any new code and so if you think its use here is idiomatic I have no complaints.

So yeah, primarily `DSP` and `DoubleFloats` seem to me like dependencies that don't need to be pulled in. If there are no objections I'm happy to make the PR that changes it and I really do appreciate that you actually took the initiative and did the work to create the package, so I hope this doesn't read as bratty. Just making an issue first to discuss in case there are objections or people want to discuss.

**Comment by daanhb** [comment]
Thanks for looking into this:
* I don't know about 'conv'. Maybe it was just being used in FastTransforms.jl elsewhere, and it doesn't need to be here. In that case, sure, please feel free to remove it.
* Indeed DoubleFloats is used in the tests and readme only. The idea is to check for at least one nonstandard type, to make sure that it continues to work. An alternative might be to define a silly type in the Tests module that simply wraps a Float64, and check that the type is preserved by the fft. I added it to the readme as a suggestion to those looking for a lightweight and slightly more accurate numeric type than Float64 (BigFloat is pretty slow especially when linear algebra is involved). But it does not need to be a dependency for that purpose.

**Comment by cgeoga** [comment]
Nice! Since `DoubleFloats` is only used in those places, how about I just add it to the test dependencies instead? We can then keep the nice tests, but it won't get pulled in just with `using GenericFFT` anymore.

**Comment by daanhb** [comment]
Ah, I thought that's what I did, but indeed I didn't. It was the plan anyway.

**Comment by cgeoga** [comment]
Fantastic. I'll send in a PR that does those things. Thanks again for putting this together!
